name: Tests

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    name: Test action
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Import role into Ansible Galaxy
        if: ${{ github.repository_owner == 'gantsign' }}
        uses: ./
        with:
          api-key: ${{ secrets.GALAXY_API_KEY }}
          github-repository: gantsign/ansible-role-java
